<?php
/*
 * This file was generated by the SjopetSoapClientGeneratorBundle.
 *
 * Sjoerd Peters <speters@sjopet.net>
 * 23-02-2012
 *
 * For more information please visit:
 * https://bitbucket.org/sjopet/sf2bundle-soap-client-generator
 */

namespace {{ namespace }}\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
{% if 'annotation' == format -%}
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
{%- endif %}

class DefaultController extends Controller
{

    {% if 'annotation' == format -%}
    /**
     * @Route("/hello")
     * @Template()
     */
    {%- endif %}

    public function indexAction()
    {
        {% for service in services -%}
        $service = $this->container->get('{{ extension_alias }}.{{ service.name }}.service');
        {%- endfor %}
        $serverInfo = $service->getServerInfo('');
        $info = '';
        $info .= '<br/>';
        $info .= 'baseUrl: '.$serverInfo->getBaseurl();
        $info .= '<br/>';
        $info .= 'buildDate: '.$serverInfo->getBuilDdate();
        $info .= '<br/>';
        $info .= 'buildNumber: '.$serverInfo->getBuildNumber();
        $info .= '<br/>';
        $timeInfo = $serverInfo->getServerTime();
        $info .= 'serverTime: '.$timeInfo->getServerTime();
        $info .= '<br/>';
        $info .= 'version: '.$serverInfo->getVersion();
        $info .= '<br/>';

        {% if 'annotation' != format -%}
        return $this->render('{{ bundle }}:Default:index.html.twig', array('info' => $info));
        {%- else -%}
        return array();
        {%- endif %}

    }
}
