<?php
/*
 * This file was generated by the SjopetSoapClientGeneratorBundle.
 *
 * Sjoerd Peters <speters@sjopet.net>
 * 23-02-2012
 *
 * For more information please visit:
 * https://bitbucket.org/sjopet/sf2bundle-soap-client-generator
 */

namespace {{ namespace }}\Tests\Controller;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class DefaultControllerTest extends WebTestCase
{
    public function testIndex()
    {
        $client = static::createClient();

        $crawler = $client->request('GET', '/hello/Fabien');

        $this->assertTrue($crawler->filter('html:contains("Hello Fabien")')->count() > 0);
    }
}
