<?php
/*
 * This file was generated by the SjopetSoapClientGeneratorBundle.
 *
 * Sjoerd Peters <speters@sjopet.net>
 * 23-02-2012
 *
 * For more information please visit:
 * https://bitbucket.org/sjopet/sf2bundle-soap-client-generator
 */

use Symfony\Component\DependencyInjection\Definition;
use Symfony\Component\DependencyInjection\Reference;
use Symfony\Component\DependencyInjection\Parameter;


$container->setParameter('{{ extension_alias }}.wsdl', '');
{% for service in services %}
$container->setParameter('{{ extension_alias }}.{{ service.name }}', '{{ namespace }}\Service\{{ service.class }}');
{% endfor -%}

{% for service in services %}
$container->setDefinition(
    '{{ extension_alias }}.{{ service.name }}.service',
    new Definition(
        '%{{ extension_alias }}.{{ service.name }}%',
        array(
            "%{{ extension_alias }}.wsdl%",
            new Reference('validator'),
        )
    )
);
{% endfor -%}

