<?php
/*
 * This file was generated by the SjopetSoapClientGeneratorBundle.
 *
 * Sjoerd Peters <speters@sjopet.net>
 * 23-02-2012
 *
 * For more information please visit:
 * https://bitbucket.org/sjopet/sf2bundle-soap-client-generator
 */

namespace {{ namespace }}\Model;

class {{ class }} {{ extends }}
{

{%- for property in properties %}
    protected ${{ property.name }};
{%- endfor -%}

{% for property in properties %}

    /**
     * @param {% if property.custom %}\{{ namespace }}\Model\{% endif %}{{ property.type }} ${{ property.name }}
     * @return \{{ namespace }}\Model\{{ class }}
     */
    public function set{{ property.funcName }}(${{ property.name }})
    {
        $this->{{ property.name }} = ${{ property.name }};
        return $this;
    }

    /**
     * @return {% if property.custom %}\{{ namespace }}\Model\{% endif %}{{ property.type }}
     */
    public function get{{ property.funcName }}()
    {
        return $this->{{ property.name }};
    }
{% endfor %}
}
