<?php
/*
 * This file was generated by the SjopetSoapClientGeneratorBundle.
 *
 * Sjoerd Peters <speters@sjopet.net>
 * 23-02-2012
 *
 * For more information please visit:
 * https://bitbucket.org/sjopet/sf2bundle-soap-client-generator
 */

namespace {{ namespace }}\Service;

interface ParameterInterface
{
    /**
     * @abstract
     * @return array
     */
    public function getArguments();
}
